version: '3.7'

services:
  postgres:
    container_name: iot_postgres
    image: postgres:16.1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
       - ./docker_iot_db:/data
    ports:
      - "5432:5432"
    networks:
      - net
  node-red:
    container_name: iot_node-red
    image: nodered/node-red:3.1.3
    environment:
      - TZ=Europe/London
    ports:
      - "1880:1880"
    volumes:
      - ./node-red-data:/data
    networks:
      - net
volumes:
  postgres-db:
    driver: local
  node-red-data:
    driver: local
networks:
    net:
